### ISSUE TITLE
更新之后

### ISSUE THREAD

**Issue by Nappp** [larsenlouis/qian-ni-mei#1]
以前的版本放vps上只要添加了账号往cron.daily一丢就行 现在必须放参数就有点过于方便了

**Comment by larsenlouis** [comment]
考虑到可能会出现一个脚本对用个账号签到的情况，所以用到了参数传递。 你可以在一个脚本里带上参数写qian-ni-mei-desktop.sh的命令，再扔到cron.daily。是有点麻烦，见谅。
