### ISSUE TITLE
请问, 这个 sh 可以丢到路由器里去运行吗? 我的路由器刷了 merlin 固件, 貌似支持 sh 脚本

### ISSUE THREAD

**Issue by heeroyuyj** [larsenlouis/qian-ni-mei#2]
但是不知道如何实现? 如果能实现, 这个脚本是让它定期运行还是它会自动运行?

**Comment by larsenlouis** [comment]
最简单的方法是使用0aa8(display info from json)版，然后参照https://github.com/RMerl/asuswrt-merlin/blob/master/README-merlin.txt#L262添加到cron
