### ISSUE TITLE
签到失败：请先进入签到页面或者你的停留时间太长

### ISSUE THREAD

**Issue by ojeo** [larsenlouis/qian-ni-mei#3]
签你妹 session starts at 2015-05-24 00:00:14 UTC+0000
Requesting login page....
Sending your account confidential...
Server response to your login info: 0=failed, 1=succeeded
bad argument(s).
ZiMuZu.tv also says: badarg\ument(s).
Please wait for 5 seconds as page-rediect simulation...
Requesting user home page...
Please wait for 20 seconds as js-button-timer simulation...
Sending your sign request...
Server response to your sign: 0=failed, 1=successed
4002
ZiMuZu.tv also says: 请先进入签到页面或者你的停留时间太长
Cleaning up cookies...
Done!
签你妹 session ends at 2015-05-24 00:01:13 UTC+0000

**Comment by larsenlouis** [comment]
bad argument(s). 参数不对 请检查用户名 密码

**Comment by ojeo** [comment]
我知道参数不对……但是实际上 我是用服务器的脚本 连续签到7天，第8天报这个错。
代码我自己改了一下，只是跟你说一下有这个情况……

**Comment by larsenlouis** [comment]
@ojeo 疑似是ajaxlogin post请求参数问题 已修复
